In [12]:
import numpy as np
import torch
import time

### 1.Performance comparison of tensor numpy and list

In [13]:
size = 1_000_000

a = list(range(size))
b = list(range(size))

start = time.time()

c = [a[i] + b[i] for i in range(size)]

end = time.time()

In [14]:
a = np.arange(size)
b = np.arange(size)

start = time.time()

c = a + b

end = time.time()

In [15]:
a = torch.arange(size)
b = torch.arange(size)

start = time.time()

c = a + b

end = time.time()

In [16]:
print("List time:", end - start)
print("NumPy time:", end - start)
print("PyTorch CPU time:", end - start)

List time: 0.00420379638671875
NumPy time: 0.00420379638671875
PyTorch CPU time: 0.00420379638671875


### 2.CREATING 1D 2D AND 3D TENSORS USING PYTORCH AND NUMPY

In [17]:
arr1 = np.array([1,2,3])
arr2 = np.array([[1,2,3],[4,5,6]])
arr3 = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])

print(arr1.shape)
print(arr2.shape)
print(arr3.shape)

(3,)
(2, 3)
(2, 2, 3)


In [18]:
arr1 = torch.tensor([1,2,3])
arr2 = torch.tensor([[1,2,3],[4,5,6]])
arr3 = torch.tensor([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])

print(arr1.shape)
print(arr2.shape)
print(arr3.shape)

torch.Size([3])
torch.Size([2, 3])
torch.Size([2, 2, 3])


### 3. Element-wise operations

In [19]:
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])

print(arr1+arr2)
print(arr1-arr2)
print(arr1*arr2)
print(arr1/arr2)

[5 7 9]
[-3 -3 -3]
[ 4 10 18]
[0.25 0.4  0.5 ]


In [20]:
arr1 = torch.tensor([1,2,3])
arr2 = torch.tensor([4,5,6])

print(arr1+arr2)
print(arr1-arr2)
print(arr1*arr2)
print(arr1/arr2)

tensor([5, 7, 9])
tensor([-3, -3, -3])
tensor([ 4, 10, 18])
tensor([0.2500, 0.4000, 0.5000])


### 4. Indexing and Slicing operations

In [21]:
a = np.array([[10,20,30] , [40,50,60]])

In [22]:
b = torch.tensor([[10,20,30],[40,50,60]])

In [23]:
## basic indexing and slicing

In [24]:
print(a[0, 1])
print(a[:, 1])

20
[20 50]


In [25]:
print(b[0, 1])
print(b[:, 1])

tensor(20)
tensor([20, 50])


In [26]:
## boolean masking

In [27]:
x = np.array([1, 2, 3, 4, 5])
mask = x > 3
print(x[mask])

[4 5]


In [28]:
y = torch.tensor([1, 2, 3, 4, 5])
mask = y > 3
print(y[mask])

tensor([4, 5])


In [29]:
## extracting subtensors

In [30]:
print(a[0:2, 1:3])

[[20 30]
 [50 60]]


In [31]:
print(b[0:2, 1:3])

tensor([[20, 30],
        [50, 60]])


### 5.Shape Manipulation in Pytorch

In [32]:
## view : It works if the memory allocated to tensor is continuous

In [33]:
x = torch.arange(6)
print(x)
y = x.view(2, 3)
print(y)

tensor([0, 1, 2, 3, 4, 5])
tensor([[0, 1, 2],
        [3, 4, 5]])


In [34]:
## reshape

In [35]:
z = x.reshape(3,2)
print(z)

tensor([[0, 1],
        [2, 3],
        [4, 5]])


In [36]:
## unsqueeze

In [37]:
a = torch.tensor([1,2,3])

print(a.shape)          # [3]
print(a.unsqueeze(0))   # [1, 3]
print(a.unsqueeze(1))   # [3, 1]

torch.Size([3])
tensor([[1, 2, 3]])
tensor([[1],
        [2],
        [3]])


In [38]:
## squeeze

In [39]:
b = torch.tensor([[1,2,3]])

print(b.shape)
print(b.squeeze(0))

torch.Size([1, 3])
tensor([1, 2, 3])


### 6.Numpy reshape comparison

In [40]:
x = np.arange(6)
print(x.reshape(2,3))

[[0 1 2]
 [3 4 5]]


### 7. Broadcasting

In [41]:
a = np.array([[1, 2, 3]])
b = np.array([10, 20, 30])
print(a + b)

[[11 22 33]]


In [42]:
a = torch.tensor([[1, 2, 3]])
b = torch.tensor([10, 20, 30])
print(a + b)

tensor([[11, 22, 33]])


### 8. In-place vs Out-of-place operations

In [43]:
x = torch.tensor([1, 2, 3])
y = x + 1

print(x)
print(y)

tensor([1, 2, 3])
tensor([2, 3, 4])


In [44]:
x = torch.tensor([1, 2, 3])
x.add_(1)   # note the underscore

print(x)

tensor([2, 3, 4])
